name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"
          scope: "@marcduez"

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - run: yarn test --ci

      - run: yarn build

      - run: cp {package.json,README.md} dist

      - run: yarn publish dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
